-- return {
--   "sphamba/smear-cursor.nvim",
--   opts = {
--     stiffness = 0.8,
--     trailing_stiffness = 0.6,
--     distance_stop_animating = 0.8,
--     cursor_color = nil,
--     hide_target_hack = false,
--     smear_between_buffers = true,
--     smear_between_neighbor_lines = true,
--     scroll_buffer_space = true,
--     legacy_computing_symbols_support = false,
--     smear_insert_mode = true,
--   },
-- }
